### ISSUE TITLE
No module named 'execjs'

### ISSUE THREAD

**Issue by Oppswhite** [1dooooo/hsup_sserpxe#6]
在使用adduser和additem添加完参数后，运行main.py会直接报错，
`Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from proxy import detail_proxy, belong_to_proxy
  File "C:\phpStudy\PHPTutorial\WWW\proxy.py", line 3, in <module>
    from api import belong_trackingmore_api, datail_cainiao_api, detail_trackingmore_api
  File "C:\phpStudy\PHPTutorial\WWW\api\detail_trackingmore_api.py", line 1, in <module>
    import execjs
ImportError: No module named 'execjs'`
没改动任何文件

**Comment by 1dooooo** [comment]
需要execjs库支持api中js加密的解密。
